### ISSUE TITLE
[Question] Turret

### ISSUE THREAD

**Issue by Niconoko** [GoldenKittenPlays/FairAI#1]
Is this make turrets shoot enemies too? (´・ω・｀)?

**Comment by GoldenKittenPlays** [comment]
This currently only makes mines work but I am always keeping up on updates so Turrets should work too within the next few days. Thanks for your interest nya.

**Comment by GoldenKittenPlays** [comment]
I have now added TurretAI. Please enjoy and tell me your thoughts
