### ISSUE TITLE
Turrets not targeting or damaging enemies

### ISSUE THREAD

**Issue by UmaLPZ** [GoldenKittenPlays/FairAI#10]
Love the mod. Unfortunately it looks like the turrets aren't targeting enemies. I've seen this happen with the bracken, spore, and nutcracker. I've tried baiting the turret to shoot at me while the enemy was between me and the turret and the turret doesn't seem to damage them. They are all enabled in the config and they can blow up mines just fine. It's just the turrets that seem to be ignoring them.

**Comment by UmaLPZ** [comment]
No worries and no rush on this. I also assumed it was another mod interfering with the turrets.  It might be the Lategame Upgrades mod that is interfering since it's the only one my friends and I use that affects turrets in some way.

**Comment by GoldenKittenPlays** [comment]
> No worries and no rush on this. I also assumed it was another mod interfering with the turrets. It might be the Lategame Upgrades mod that is interfering since it's the only one my friends and I use that affects turrets in some way.

Gotcha I will take a look soon

**Comment by RandomSynesthetic** [comment]
Turret does damage the nutcracker, but does not target it. The nutcracker head has to pop up and show the eye for it to take damage

**Comment by UmaLPZ** [comment]
Oh I think RandomSynesthetic might be right. But the nutcracker's head was popped up and wasn't getting damaged from the turret. The turrets does target other monsters though. Looks like it was just the nutcracker that made it look like it was bugged.

**Comment by GoldenKittenPlays** [comment]
> Oh I think RandomSynesthetic might be right. But the nutcracker's head was popped up and wasn't getting damaged from the turret. The turrets does target other monsters though. Looks like it was just the nutcracker that made it look like it was bugged.

I have started work on them again because I have time now. Not exactly much time because now next months rent looms over my head. I will try and see why this is an issue but thanks for the report.

**Comment by Kuroo2021** [comment]
I would like to add to the report now that turrets don't do anything when FairAI is turn on, they just sit there doing nothing not turning left to right or such there just dead in the water. This is in V50, I disable all my mods to find out which on was giving the issues to the game.

**Comment by GoldenKittenPlays** [comment]
> I would like to add to the report now that turrets don't do anything when FairAI is turn on, they just sit there doing nothing not turning left to right or such there just dead in the water. This is in V50, I disable all my mods to find out which on was giving the issues to the game.

Please send me your log file. This can be found inside your bepinex folder in the game files

**Comment by Kuroo2021** [comment]
> Please send me your log file. This can be found inside your bepinex folder in the game files

![Logs](https://github.com/GoldenKittenPlays/FairAI/assets/18900059/c89c025d-b84c-4b80-8beb-8b6b22167194)

Looking in the steam install directory there seems to be no such Bepinex folder, could you give a path as where it may be at?

**Comment by GoldenKittenPlays** [comment]
> > Please send me your log file. This can be found inside your bepinex folder in the game files
> 
> ![Logs](https://private-user-images.githubusercontent.com/18900059/334073493-c89c025d-b84c-4b80-8beb-8b6b22167194.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzM4MDIsIm5iZiI6MTcxNjgzMzUwMiwicGF0aCI6Ii8xODkwMDA1OS8zMzQwNzM0OTMtYzg5YzAyNWQtYjg0Yy00YjgwLThiZWItOGI2YjIyMTY3MTk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE4MTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYjY3MzllZjI3MTY2OTc0YjZjMjVlNmZjMzg5M2JjY2VmYjNkMDkzZTU2MWRmNGM0MDNhNjcwNDdlZjllYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z_BK4RW2E5Lxciwl7YHNzM7JHH_vWzNf7zIMYTeryTc)
> 
> Looking in the steam install directory there seems to be no such Bepinex folder, could you give a path as where it may be at?

Should be under Lethal Company_Data folder. Thanks for the update

**Comment by Kuroo2021** [comment]
> > > Please send me your log file. This can be found inside your bepinex folder in the game files
> > 
> > 
> > ![Logs](https://private-user-images.githubusercontent.com/18900059/334073493-c89c025d-b84c-4b80-8beb-8b6b22167194.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzM4MDIsIm5iZiI6MTcxNjgzMzUwMiwicGF0aCI6Ii8xODkwMDA1OS8zMzQwNzM0OTMtYzg5YzAyNWQtYjg0Yy00YjgwLThiZWItOGI2YjIyMTY3MTk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE4MTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYjY3MzllZjI3MTY2OTc0YjZjMjVlNmZjMzg5M2JjY2VmYjNkMDkzZTU2MWRmNGM0MDNhNjcwNDdlZjllYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z_BK4RW2E5Lxciwl7YHNzM7JHH_vWzNf7zIMYTeryTc)
> > Looking in the steam install directory there seems to be no such Bepinex folder, could you give a path as where it may be at?
> 
> Should be under Lethal Company_Data folder. Thanks for the update

Call me crazy but even with in this folder there is no Bepinex folder
![Screenshot Y](https://github.com/GoldenKittenPlays/FairAI/assets/18900059/1906aeb8-e719-46fc-bb43-4fc105e07499)

I use r2modman and run mods with no issues.

**Comment by GoldenKittenPlays** [comment]
> > > > Please send me your log file. This can be found inside your bepinex folder in the game files
> > > 
> > > 
> > > ![Logs](https://private-user-images.githubusercontent.com/18900059/334073493-c89c025d-b84c-4b80-8beb-8b6b22167194.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzM4MDIsIm5iZiI6MTcxNjgzMzUwMiwicGF0aCI6Ii8xODkwMDA1OS8zMzQwNzM0OTMtYzg5YzAyNWQtYjg0Yy00YjgwLThiZWItOGI2YjIyMTY3MTk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE4MTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYjY3MzllZjI3MTY2OTc0YjZjMjVlNmZjMzg5M2JjY2VmYjNkMDkzZTU2MWRmNGM0MDNhNjcwNDdlZjllYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z_BK4RW2E5Lxciwl7YHNzM7JHH_vWzNf7zIMYTeryTc)
> > > Looking in the steam install directory there seems to be no such Bepinex folder, could you give a path as where it may be at?
> > 
> > 
> > Should be under Lethal Company_Data folder. Thanks for the update
> 
> Call me crazy but even with in this folder there is no Bepinex folder ![Screenshot Y](https://private-user-images.githubusercontent.com/18900059/334255226-1906aeb8-e719-46fc-bb43-4fc105e07499.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjczNjEsIm5iZiI6MTcxNjg2NzA2MSwicGF0aCI6Ii8xODkwMDA1OS8zMzQyNTUyMjYtMTkwNmFlYjgtZTcxOS00NmZjLWJiNDMtNGZjMTA1ZTA3NDk5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAzMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNTFmN2MxN2ZmZjVjMjc5NGYxOTM1ZTNjOGNjZTBlM2EyN2ZlZWMxMzI5MjBlZDQzODRhNjkxZTE4YzE5OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._tWcMb-iVHa4oCuqM8q6oxB0Udeo0XBtVCtmwx3Kvxo)
> 
> I use r2modman and run mods with no issues.

How are you modding then? If it is through something like modman or thunderstore then you need to open up the profile folder not your game folder. Otherwise I got no clue because bepinex shows up in my folder 
![image](https://github.com/GoldenKittenPlays/FairAI/assets/134951434/dbac2cc8-722e-41b5-8353-daa97f551481)

**Comment by Kuroo2021** [comment]
> > > > > Please send me your log file. This can be found inside your bepinex folder in the game files
> > > > 
> > > > 
> > > > ![Logs](https://private-user-images.githubusercontent.com/18900059/334073493-c89c025d-b84c-4b80-8beb-8b6b22167194.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzM4MDIsIm5iZiI6MTcxNjgzMzUwMiwicGF0aCI6Ii8xODkwMDA1OS8zMzQwNzM0OTMtYzg5YzAyNWQtYjg0Yy00YjgwLThiZWItOGI2YjIyMTY3MTk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE4MTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYjY3MzllZjI3MTY2OTc0YjZjMjVlNmZjMzg5M2JjY2VmYjNkMDkzZTU2MWRmNGM0MDNhNjcwNDdlZjllYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z_BK4RW2E5Lxciwl7YHNzM7JHH_vWzNf7zIMYTeryTc)
> > > > Looking in the steam install directory there seems to be no such Bepinex folder, could you give a path as where it may be at?
> > > 
> > > 
> > > Should be under Lethal Company_Data folder. Thanks for the update
> > 
> > 
> > Call me crazy but even with in this folder there is no Bepinex folder ![Screenshot Y](https://private-user-images.githubusercontent.com/18900059/334255226-1906aeb8-e719-46fc-bb43-4fc105e07499.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjczNjEsIm5iZiI6MTcxNjg2NzA2MSwicGF0aCI6Ii8xODkwMDA1OS8zMzQyNTUyMjYtMTkwNmFlYjgtZTcxOS00NmZjLWJiNDMtNGZjMTA1ZTA3NDk5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAzMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNTFmN2MxN2ZmZjVjMjc5NGYxOTM1ZTNjOGNjZTBlM2EyN2ZlZWMxMzI5MjBlZDQzODRhNjkxZTE4YzE5OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._tWcMb-iVHa4oCuqM8q6oxB0Udeo0XBtVCtmwx3Kvxo)
> > I use r2modman and run mods with no issues.
> 
> How are you modding then? If it is through something like modman or thunderstore then you need to open up the profile folder not your game folder. Otherwise I got no clue because bepinex shows up in my folder ![image](https://private-user-images.githubusercontent.com/134951434/334259363-dbac2cc8-722e-41b5-8353-daa97f551481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzAzNTEsIm5iZiI6MTcxNjg3MDA1MSwicGF0aCI6Ii8xMzQ5NTE0MzQvMzM0MjU5MzYzLWRiYWMyY2M4LTcyMmUtNDFiNS04MzUzLWRhYTk3ZjU1MTQ4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQwNDIwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjNlNjI4OWEzODFkOGFmMGE2OWU2OTI2MmZjZjNmYTdhOWZlODE3MzRmYTE3OTUxODlhNmVmMjZiYmQyMjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V_EjNUN6XogM_kez2od7DWKO5BB1xb2bLoRTlsulaHA)

I'm using R2modman, okay I see it now, referring  the location helped. 
[LogOutput.log](https://github.com/GoldenKittenPlays/FairAI/files/15463923/LogOutput.log)

I can also do a video to show the different when FairAI is on and off.

**Comment by GoldenKittenPlays** [comment]
> > > > > > Please send me your log file. This can be found inside your bepinex folder in the game files
> > > > > 
> > > > > 
> > > > > ![Logs](https://private-user-images.githubusercontent.com/18900059/334073493-c89c025d-b84c-4b80-8beb-8b6b22167194.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzM4MDIsIm5iZiI6MTcxNjgzMzUwMiwicGF0aCI6Ii8xODkwMDA1OS8zMzQwNzM0OTMtYzg5YzAyNWQtYjg0Yy00YjgwLThiZWItOGI2YjIyMTY3MTk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE4MTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYjY3MzllZjI3MTY2OTc0YjZjMjVlNmZjMzg5M2JjY2VmYjNkMDkzZTU2MWRmNGM0MDNhNjcwNDdlZjllYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z_BK4RW2E5Lxciwl7YHNzM7JHH_vWzNf7zIMYTeryTc)
> > > > > Looking in the steam install directory there seems to be no such Bepinex folder, could you give a path as where it may be at?
> > > > 
> > > > 
> > > > Should be under Lethal Company_Data folder. Thanks for the update
> > > 
> > > 
> > > Call me crazy but even with in this folder there is no Bepinex folder ![Screenshot Y](https://private-user-images.githubusercontent.com/18900059/334255226-1906aeb8-e719-46fc-bb43-4fc105e07499.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjczNjEsIm5iZiI6MTcxNjg2NzA2MSwicGF0aCI6Ii8xODkwMDA1OS8zMzQyNTUyMjYtMTkwNmFlYjgtZTcxOS00NmZjLWJiNDMtNGZjMTA1ZTA3NDk5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAzMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNTFmN2MxN2ZmZjVjMjc5NGYxOTM1ZTNjOGNjZTBlM2EyN2ZlZWMxMzI5MjBlZDQzODRhNjkxZTE4YzE5OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._tWcMb-iVHa4oCuqM8q6oxB0Udeo0XBtVCtmwx3Kvxo)
> > > I use r2modman and run mods with no issues.
> > 
> > 
> > How are you modding then? If it is through something like modman or thunderstore then you need to open up the profile folder not your game folder. Otherwise I got no clue because bepinex shows up in my folder ![image](https://private-user-images.githubusercontent.com/134951434/334259363-dbac2cc8-722e-41b5-8353-daa97f551481.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzAzNTEsIm5iZiI6MTcxNjg3MDA1MSwicGF0aCI6Ii8xMzQ5NTE0MzQvMzM0MjU5MzYzLWRiYWMyY2M4LTcyMmUtNDFiNS04MzUzLWRhYTk3ZjU1MTQ4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQwNDIwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjNlNjI4OWEzODFkOGFmMGE2OWU2OTI2MmZjZjNmYTdhOWZlODE3MzRmYTE3OTUxODlhNmVmMjZiYmQyMjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V_EjNUN6XogM_kez2od7DWKO5BB1xb2bLoRTlsulaHA)
> 
> I'm using R2modman, okay I see it now, referring the location helped. [LogOutput.log](https://github.com/GoldenKittenPlays/FairAI/files/15463923/LogOutput.log)
> 
> I can also do a video to show the different when FairAI is on and off.

Gotcha I mean anything helps but only do what you want to lol I should be able to figure something out with the log as long as it was the last session where you had FairAI in use during your latest time playing the game

**Comment by dmon257** [comment]
Hello there, i also have this issue to the tune of i have never seen the turret ever target anything other than players. i do run my modset kinda weird though, as long as sever side has it installed other people who don't have it installed still have the mines explode on contact with enemy, but the turret does not target as advertised even solo.
ill see if i can get on tape

**Comment by GoldenKittenPlays** [comment]
> Quote reply

Turrets currently only support damaging enemies not targeting. Fixing this feature atm

**Comment by GoldenKittenPlays** [comment]
Fixed
