### ISSUE TITLE
Neither turrets nor bombs do not kill anyone

### ISSUE THREAD

**Issue by DeadseaX** [GoldenKittenPlays/FairAI#11]
Neither turrets nor bombs do not kill anyone, it used to work, now it stopped, also maybe there is a conflict with everyone dies, but even both mods separately can not make anyone die, yes activate bombs and explode, turrets shoot, but do not kill, I have already rebropoval all, also both mods are almost identical, it would not be worth it to combine them to avoid all conflicts and this has grown into something global, I have a unique server and this mod used to work I have my own development like brutal company and specifically need to mine to die from mobs(((

I hope to fix it soon, I do not understand why it broke, I can send both video and screens, but I have already tried all the values and so on, also the second joint your mod on all die can not kill with a poke jester and spring, it's a pity

**Comment by DeadseaX** [comment]
I can also share the build, it is quite large, also I would like to do it personally, because we have a unique customized hodgepodge that no one has seen, but everything worked, added a little mods, maybe they after updates somehow conflicted became, also there is such a thing when the mob died he in the animation of the living freezes and can even kill any player, the spider bites, the lollipop shoots while lying down

**Comment by DeadseaX** [comment]
Well here is further check, the mod simply stopped working even if only he and the sea company installed, or rather not completely explode no one can not, but to activate the turret or mine yes

**Comment by GoldenKittenPlays** [comment]
> Well here is further check, the mod simply stopped working even if only he and the sea company installed, or rather not completely explode no one can not, but to activate the turret or mine yes

Please send me a video and screenshots. Also would love to see the log file which can be found in your profile. You go to the bepinex folder in the profile and then the log file.

**Comment by DeadseaX** [comment]
More about EverythingCanDie, version 2.5 works, the mobs explode, but it has broken khp mobs, always with 2 hits die, but FairAi fully working early or fresh could not find, another mod above 2.5 also works already incorrectly, but I personally need both mods, change khp, set the explosion or aiming turrets, very much waiting for when you make it a single mod
[LogOutput.log](https://github.com/GoldenKittenPlays/FairAI/files/14156985/LogOutput.log)


https://github.com/GoldenKittenPlays/FairAI/assets/44456040/ffd4e262-5283-4470-a178-2c6ce3cce800

**Comment by DeadseaX** [comment]
On the video works activation and turrets and mines, but no one dies again, mods I have a minimum is minimal, especially for the test turned off, but as practice has shown the matter is not in it

**Comment by GoldenKittenPlays** [comment]
So in your log there is something called CheatBossAntiCheat. Try disabling that and see if it works.

The log I mentioned:

CheatBossAntiCheat.Patches.EnemyHitAction (EnemyAI __instance, System.Int32 force, System.Int32 playerWhoHit, System.Boolean playHitSFX) (at <8aed24d1ebe147cf9766ad31468ca8bd>:0)
(wrapper dynamic-method) EnemyAI.DMD<EnemyAI::HitEnemyServerRpc>(EnemyAI,int,int,bool)
EnemyAI.HitEnemyOnLocalClient (System.Int32 force, UnityEngine.Vector3 hitDirection, GameNetcodeStuff.PlayerControllerB playerWhoHit, System.Boolean playHitSFX) (at <af9b1eec498a45aebd42601d6ab85015>:0)
FairAI.Plugin+<>c__DisplayClass29_0.<HitTargets>b__0 (UnityEngine.GameObject t) (at <dad4ccc497a84233b9f7eba104980a28>:0)
System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) (at <787acc3c9a4c471ba7d971300105af24>:0)
FairAI.Plugin.HitTargets (System.Collections.Generic.List`1[T] targets, UnityEngine.Vector3 forward) (at <dad4ccc497a84233b9f7eba104980a28>:0)
FairAI.Plugin.AttackTargets (UnityEngine.Vector3 aimPoint, UnityEngine.Vector3 forward, System.Single range) (at <dad4ccc497a84233b9f7eba104980a28>:0)
FairAI.Patches.TurretAIPatch.PatchUpdate (Turret& __instance) (at <dad4ccc497a84233b9f7eba104980a28>:0)
(wrapper dynamic-method) Turret.DMD<Turret::Update>(Turret)

**Comment by DeadseaX** [comment]
Indeed, the conflict was there, but I will still check the compatibility of the mods with each other, since when it started I was using only 1 mod and it partially worked, thanks!

**Comment by GoldenKittenPlays** [comment]
> Indeed, the conflict was there, but I will still check the compatibility of the mods with each other, since when it started I was using only 1 mod and it partially worked, thanks!

No problem feel free to tell me anything else that may go wrong here

**Comment by DeadseaX** [comment]
In general this is what came out in my full build + 2 mods and customized, their configs are also attached and a video where the mobs die before I ran out of installed xp and some die as I assigned, but can hold on and here is an example with slime, jester and licker they are dead and not, may well kill, but the loot from them has already fallen, this happens with others, often spiders hang dead but their hitbox is biting
https://drive.google.com/file/d/1yHf7cgR2kX1_B35PuHJ_gRrrS3EOQ2Mw/view?usp=sharing
https://drive.google.com/uc?id=1O5ZmaNQp51AaDhrRlDC6CE36IF4CzGRX&export=download

**Comment by DeadseaX** [comment]
@GoldenKittenPlays

**Comment by GoldenKittenPlays** [comment]
> @GoldenKittenPlays
I mean would have been easier just sending the log file. Shows me what I need to see but I can not do anything with those files for now. I will see what I can do soon

**Comment by DeadseaX** [comment]
Okay, I'm waiting, but I attached the log and configs to make it clearer where I was wrong, or what the problem is even if I'm not wrong

**Comment by DeadseaX** [comment]
@GoldenKittenPlays 
What's the news there?

**Comment by GoldenKittenPlays** [comment]
> @GoldenKittenPlays What's the news there?

I mean sorry I am working on 4 mods right now so I am trying my best to keep up on it. I will let you know if I figure out anything but so far I havent even got a playtest setup yet.

**Comment by GoldenKittenPlays** [comment]
> @GoldenKittenPlays What's the news there?

Oh I see that you forgot to enable the explosion effect for all mobs. That is the temporary solution to get rid of the enemy bodies. Because the enemies do not have a death animation some of them just stay alive if they are not forcefully removed by the explosion effect from everything can die mod

**Comment by DeadseaX** [comment]
Ooh, I thought it is not important, well, I was afraid that it may cause some errors because it is only for me, others do not see this effect, I will try to enable, thank you

**Comment by GoldenKittenPlays** [comment]
> Ooh, I thought it is not important, well, I was afraid that it may cause some errors because it is only for me, others do not see this effect, I will try to enable, thank you

Of course no problem and that was the original intention but sadly I use it as a temp solution.

**Comment by DeadseaX** [comment]
![image](https://github.com/GoldenKittenPlays/FairAI/assets/44456040/3fbbe6a7-a064-42e4-9447-606dfb0f7933)
Something is still wrong, the bodies even after the explosion do not disappear, and the other player they are alive and hang in place, or braken dead I constantly break the neck of my immortal friend, the value is worth, the explosion was, the body remained....
[LogOutput.log](https://github.com/GoldenKittenPlays/FairAI/files/14213784/LogOutput.log)

**Comment by DeadseaX** [comment]
And I forgot to mention again, their hp is not equal to what I set, it's less, the mask needs not 6 but 3 hits which is strange
