### ISSUE TITLE
no have confing file 

### ISSUE THREAD

**Issue by freezaer** [GoldenKittenPlays/FairAI#13]
I can't find the confing file to edit, neither lethallib nor r2modman can see it.

**Comment by GoldenKittenPlays** [comment]
> I can't find the confing file to edit, neither lethallib nor r2modman can see it.
It is not under TheFluff but is under GoldenKitten. So the file would be called GoldenKitten.FairAi

**Comment by freezaer** [comment]
there is no file with this name, and even if there is such a configuration file, it is not seen either by mods for changing the configuration of mods, or by r2modman itself, which have the ability to read and change the configuration of mods

**Comment by GoldenKittenPlays** [comment]
> there is no file with this name, and even if there is such a configuration file, it is not seen either by mods for changing the configuration of mods, or by r2modman itself, which have the ability to read and change the configuration of mods

I use Thunderstore and it works fine in generating the config file so i mean i will check r2modman

**Comment by GoldenKittenPlays** [comment]
> I am running into the same issue. In earlier versions (about 6 months ago) it used to work just fine but now it just does not generate a config file. Did you find any fixes or similar as to why this happens?
> 
> My modpack: 0198dd80-07ce-2fa1-c5aa-106f7d42effe
> 
> ### Attachments
> Installed: <img alt="Image" width="782" height="352" src="https://private-user-images.githubusercontent.com/192270685/481404732-0fb645fe-4333-4b68-9877-b9313da7ab29.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY1MTM2NzksIm5iZiI6MTc1NjUxMzM3OSwicGF0aCI6Ii8xOTIyNzA2ODUvNDgxNDA0NzMyLTBmYjY0NWZlLTQzMzMtNGI2OC05ODc3LWI5MzEzZGE3YWIyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgzMFQwMDIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTVhOGJiOGMxNmYzZjczNzgzMGZmNTFiZDlhNjczYzJkNTJkNjMyYTg3M2ViZDVlMzhiYTkyODAwMDYxNzZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0D0V8_1hrCUw8JWYOPLJrPMDnVxjwnShSg-wMSyBO6k">
> 
> In my configs: <img alt="Image" width="1628" height="281" src="https://private-user-images.githubusercontent.com/192270685/481404706-8839912b-4fce-4ee9-ab88-f863e8362357.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY1MTM2NzksIm5iZiI6MTc1NjUxMzM3OSwicGF0aCI6Ii8xOTIyNzA2ODUvNDgxNDA0NzA2LTg4Mzk5MTJiLTRmY2UtNGVlOS1hYjg4LWY4NjNlODM2MjM1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgzMFQwMDIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjQ0YTkxNDJhYWJjNmY4ZmFkZjM5ZTc0ZmU5NzE3NTRhN2E0YmEyN2Y3ZDJiZWNiODE3NmRjNDY5YzE3YWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eor6DOglPSbEv3WnZwXD-5TcdUEdZoZSLh7lSqyVK_A">

So you did start up the game first correct? The config file usually generates after running the game. To be sure I usually do a quick landing in the ship first then close the game and it usually will properly make the config file

**Comment by Shaydelity** [comment]
> > I am running into the same issue. In earlier versions (about 6 months ago) it used to work just fine but now it just does not generate a config file. Did you find any fixes or similar as to why this happens?
> > 
> > My modpack: 0198dd80-07ce-2fa1-c5aa-106f7d42effe
> > 
> > ### Attachments
> > Installed: <img alt="Image" width="782" height="352" src="https://private-user-images.githubusercontent.com/192270685/481404732-0fb645fe-4333-4b68-9877-b9313da7ab29.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY1MTM2NzksIm5iZiI6MTc1NjUxMzM3OSwicGF0aCI6Ii8xOTIyNzA2ODUvNDgxNDA0NzMyLTBmYjY0NWZlLTQzMzMtNGI2OC05ODc3LWI5MzEzZGE3YWIyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgzMFQwMDIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTVhOGJiOGMxNmYzZjczNzgzMGZmNTFiZDlhNjczYzJkNTJkNjMyYTg3M2ViZDVlMzhiYTkyODAwMDYxNzZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0D0V8_1hrCUw8JWYOPLJrPMDnVxjwnShSg-wMSyBO6k">
> > 
> > In my configs: <img alt="Image" width="1628" height="281" src="https://private-user-images.githubusercontent.com/192270685/481404706-8839912b-4fce-4ee9-ab88-f863e8362357.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY1MTM2NzksIm5iZiI6MTc1NjUxMzM3OSwicGF0aCI6Ii8xOTIyNzA2ODUvNDgxNDA0NzA2LTg4Mzk5MTJiLTRmY2UtNGVlOS1hYjg4LWY4NjNlODM2MjM1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgzMFQwMDIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjQ0YTkxNDJhYWJjNmY4ZmFkZjM5ZTc0ZmU5NzE3NTRhN2E0YmEyN2Y3ZDJiZWNiODE3NmRjNDY5YzE3YWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eor6DOglPSbEv3WnZwXD-5TcdUEdZoZSLh7lSqyVK_A">
> 
> So you did start up the game first correct? The config file usually generates after running the game. To be sure I usually do a quick landing in the ship first then close the game and it usually will properly make the config file

Yes, I always do. To make sure it could generate I had it installed for entire runs but it just wouldn't generate a config. I will check with Imperium later if it even does anything currently, given it does not generate the config.

**Comment by Shaydelity** [comment]
So, apparently the mod is entirely dysfunctional for me.

<img width="743" height="226" alt="Image" src="https://github.com/user-attachments/assets/3a02e024-8275-441d-859d-9d66ae2d8b0f" />

<img width="832" height="236" alt="Image" src="https://github.com/user-attachments/assets/8c2a782d-4724-43f5-96d7-418337bfacdb" />

**Comment by GoldenKittenPlays** [comment]
> So, apparently the mod is entirely dysfunctional for me.
> 
> <img alt="Image" width="743" height="226" src="https://private-user-images.githubusercontent.com/192270685/483897086-3a02e024-8275-441d-859d-9d66ae2d8b0f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY1NzUyMzksIm5iZiI6MTc1NjU3NDkzOSwicGF0aCI6Ii8xOTIyNzA2ODUvNDgzODk3MDg2LTNhMDJlMDI0LTgyNzUtNDQxZC04NTlkLTlkNjZhZTJkOGIwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgzMFQxNzI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTM3MjU2OWMyYzA1ZDZmOTFmNTM0ZjFhNDEyYTk5MGIzMWNjYTkzMjEzMTY1ZDljZGZkY2QxYjZkZDQyZWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.USMIY863oR8SRLVWMocDuegSkuMcOsrPKURdl6fT2rs"> <img alt="Image" width="832" height="236" src="https://private-user-images.githubusercontent.com/192270685/483897114-8c2a782d-4724-43f5-96d7-418337bfacdb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY1NzUyMzksIm5iZiI6MTc1NjU3NDkzOSwicGF0aCI6Ii8xOTIyNzA2ODUvNDgzODk3MTE0LThjMmE3ODJkLTQ3MjQtNDNmNS05NmQ3LTQxODMzN2JmYWNkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgzMFQxNzI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjY5YjdkZjdhNDcxOTYzYThlNjU1M2U2ZTdjMmFkN2I3NmMwM2QzNzk5NGUyZThkYWM3MzE5ZmRkNWNlZDkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LHI5UH5SiL3LIDXDiB0OOhCagAHm3RGfWmCrmSLoDQ4">

So the odd thing is was my mod seems to load. There is no errors. There is no warnings. It just fails to create a config. So this issue might take a bit for me to understand why it will not work as there is not really anything to work with

**Comment by Shaydelity** [comment]
> > So, apparently the mod is entirely dysfunctional for me.
> > 
> > <img alt="Image" width="743" height="226" src="https://private-user-images.githubusercontent.com/192270685/483897086-3a02e024-8275-441d-859d-9d66ae2d8b0f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY1NzUyMzksIm5iZiI6MTc1NjU3NDkzOSwicGF0aCI6Ii8xOTIyNzA2ODUvNDgzODk3MDg2LTNhMDJlMDI0LTgyNzUtNDQxZC04NTlkLTlkNjZhZTJkOGIwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgzMFQxNzI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTM3MjU2OWMyYzA1ZDZmOTFmNTM0ZjFhNDEyYTk5MGIzMWNjYTkzMjEzMTY1ZDljZGZkY2QxYjZkZDQyZWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.USMIY863oR8SRLVWMocDuegSkuMcOsrPKURdl6fT2rs"> <img alt="Image" width="832" height="236" src="https://private-user-images.githubusercontent.com/192270685/483897114-8c2a782d-4724-43f5-96d7-418337bfacdb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY1NzUyMzksIm5iZiI6MTc1NjU3NDkzOSwicGF0aCI6Ii8xOTIyNzA2ODUvNDgzODk3MTE0LThjMmE3ODJkLTQ3MjQtNDNmNS05NmQ3LTQxODMzN2JmYWNkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgzMFQxNzI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjY5YjdkZjdhNDcxOTYzYThlNjU1M2U2ZTdjMmFkN2I3NmMwM2QzNzk5NGUyZThkYWM3MzE5ZmRkNWNlZDkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LHI5UH5SiL3LIDXDiB0OOhCagAHm3RGfWmCrmSLoDQ4">
> 
> So the odd thing is was my mod seems to load. There is no errors. There is no warnings. It just fails to create a config. So this issue might take a bit for me to understand why it will not work as there is not really anything to work with

Okay, so, you run into the same issue with the mod profile provided? Or is it a me-/my-pc-issue?
