### ISSUE TITLE
Turrets do not damage players.

### ISSUE THREAD

**Issue by GmeX1** [GoldenKittenPlays/FairAI#15]
Hello, the mod is pretty awesome, BUT. I had to remove it because turrets don't damage players at all. FYI, I turned off turret detection for enemies in config. Here's log:
![image](https://github.com/GoldenKittenPlays/FairAI/assets/66805207/b5efe36b-8665-434e-9900-10d9ba037748)

**Comment by GoldenKittenPlays** [comment]
> Hello, the mod is pretty awesome, BUT. I had to remove it because turrets don't damage players at all. FYI, I turned off turret detection for enemies in config. Here's log: ![image](https://private-user-images.githubusercontent.com/66805207/306339968-b5efe36b-8665-434e-9900-10d9ba037748.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NjQzMDAsIm5iZiI6MTcwODQ2NDAwMCwicGF0aCI6Ii82NjgwNTIwNy8zMDYzMzk5NjgtYjVlZmUzNmItODY2NS00MzRlLTk5MDAtMTBkOWJhMDM3NzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDIxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZjY1ZWQ0NzliZDMxNDcwMTA3ZWFhMjhiODUyOGU1N2FjNjYwZDY4ODNkNGYwMTgzNDUyYjVmODA5ZjE2MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MYZHh98owcAkW_MZDQS79hzLGuq4fGWy5AXukjxPX0w)

Thank you for the report I will probably take out targeting next update to prevent my mod from causing issues. Would love it if you can send me your log file just in case of conflicting mods

**Comment by GmeX1** [comment]
> Thank you for the report I will probably take out targeting next update to prevent my mod from causing issues. Would love it if you can send me your log file just in case of conflicting mods

How can i find the log file?

**Comment by GoldenKittenPlays** [comment]
> > Thank you for the report I will probably take out targeting next update to prevent my mod from causing issues. Would love it if you can send me your log file just in case of conflicting mods
> 
> How can i find the log file?

It is inside the bepinex folder of your profile folder and that profile folder can be found by going to settings in the Thunderstore and then click open profile folder.
