### ISSUE TITLE
Mod removes all mobs 

### ISSUE THREAD

**Issue by Covsor** [GoldenKittenPlays/FairAI#16]
With the new version, the mod began to break the game and remove absolutely all mobs from the map

**Comment by GoldenKittenPlays** [comment]
> With the new version, the mod began to break the game and remove absolutely all mobs from the map

Please send me your log our some sort of showing of it doing so please. I can not fix it with this little information but thank you for letting me know

**Comment by GoldenKittenPlays** [comment]
> > With the new version, the mod began to break the game and remove absolutely all mobs from the map
> 
> Please send me your log our some sort of showing of it doing so please. I can not fix it with this little information but thank you for letting me know

To send your log you can find it in the bepinex folder which is located in your profile folder

**Comment by s3xysteak** [comment]
I do not think it is this mod which removed all mobs. I just played with the mod and the bug could not be reproduction.

**Comment by GoldenKittenPlays** [comment]
> I do not think it is this mod which removed all mobs. I just played with the mod and the bug could not be reproduction.

Thank you I will close the issue as I could not do it either
