### ISSUE TITLE
v55 doesn't work

### ISSUE THREAD

**Issue by huluoboya3** [GoldenKittenPlays/FairAI#17]
[Info   :   BepInEx] Loading [Fair AI 1.0.0]
[Error  : Unity Log] NullReferenceException: Null method for GoldenKitten.FairAI
Stack trace:
HarmonyLib.PatchProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_001D)
HarmonyLib.Harmony.Patch (System.Reflection.MethodBase original, HarmonyLib.HarmonyMethod prefix, HarmonyLib.HarmonyMethod postfix, HarmonyLib.HarmonyMethod transpiler, HarmonyLib.HarmonyMethod finalizer, HarmonyLib.HarmonyMethod ilmanipulator) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0031)
FairAI.Plugin.CreateHarmonyPatch (HarmonyLib.Harmony harmony, System.Type typeToPatch, System.String methodToPatch, System.Type[] parameters, System.Type patchType, System.String patchMethod, System.Boolean isPrefix) (at <1e4cd2263c9d485abfcf304a8f04f54f>:IL_0068)
FairAI.Plugin.Awake () (at <1e4cd2263c9d485abfcf304a8f04f54f>:IL_00FD)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

**Comment by GoldenKittenPlays** [comment]
v55 isnt out of beta yet so until then this will remain an issue. Will be fixed upon full release
