### ISSUE TITLE
Turret targeting

### ISSUE THREAD

**Issue by jobsvigl** [GoldenKittenPlays/FairAI#19]
Might be a good idea for turrents to not target dead enemies, because they just shot with no stoping.

**Comment by GoldenKittenPlays** [comment]
Mind sending a log file it is not supposed to do it

**Comment by jobsvigl** [comment]
I wasn't the one hosting the server so i don't know if it is in the log, but when i was spectating enemies the turret killed them and kept locked on to them and was shooting for the whole duration of the game.

**Comment by jobsvigl** [comment]
https://drive.google.com/drive/folders/1bYRvB-EVZe8yao9ccIFubi55OpQcJ1gh?usp=sharing 
Here is the link for the log download, I can also get you the log from the server hoster.

**Comment by GoldenKittenPlays** [comment]
Thanks I will see what I can do and the other log would be lovely but if you can not it is ok

**Comment by ajsglist** [comment]
hey there,

I was coming to log the same bug, so I'll go ahead and drop the info here

A spider apparently nested right next to a turret and became... very dead.  I tracked down the sounds of gunfire to find the turret locked onto the spider corpse

![image](https://github.com/user-attachments/assets/daa9eb9c-e303-4998-ae82-87f42cd6149f)

Here's a full log since startup of that game session, and a log focusing on the day in question

[LogOutput.log](https://github.com/user-attachments/files/17605841/LogOutput.log)
[fair_ai_spider_murder_day.txt](https://github.com/user-attachments/files/17605844/fair_ai_spider_murder_day.txt)

**Comment by GoldenKittenPlays** [comment]
The issue with the newest update on Thunderstore seems to be resolved but if the issue occurs again feel free to tell me

**Comment by ajsglist** [comment]
I took a bit of time to test this morning, and as far as I can tell the turret behavior regarding corpse targeting has been fixed for some (most?) cases

However, when it killed a masked it continued to target the corpse

![image](https://github.com/user-attachments/assets/f4cf0b2e-21a5-49ff-85bd-4627a09e8a43)

After killing a bracken, it disintegrated like "normal" and wasn't targetted

![image](https://github.com/user-attachments/assets/d6ebbff0-e1ee-4d69-93a2-5c5f06b0006e)

In case it's relevant, the console seems to be throwing an NRE every time a turret tries to shoot a target (both player and monster I think).  It doesn't seem like a critical error, but I figured I'd note it here for you.

Cheers

![image](https://github.com/user-attachments/assets/76130a90-8442-4f54-9f9b-2b9da22226b1)
```
[12:36:15.7917569] [Info   :GoldenKitten.FairAI] Attacking Target
[12:36:15.7917569] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TurretAIPatch.FiringFunction (Turret turret) (at <22344ffe4bd64cc2ad5f3186a9987715>:IL_039B)
TurretAIPatch.PatchUpdate (Turret& __instance) (at <22344ffe4bd64cc2ad5f3186a9987715>:IL_01D7)
(wrapper dynamic-method) Turret.DMD<Turret::Update>(Turret)
```

**Comment by GoldenKittenPlays** [comment]
Oh good welp another round of digging around the code to fix it. Thanks for the report

**Comment by ajsglist** [comment]
Took some time to test the newest version (1.4.3) and I think it's been fixed.  Thanks for taking the time to work through the issue :)

Beyond that, has the turret damage to enemies been changed/nerfed?  It seems like it takes an awful lot of bullets to kill enemies.

![image](https://github.com/user-attachments/assets/e69f7e6e-0a65-4157-b9ff-512de8da1104)
![image](https://github.com/user-attachments/assets/985b9483-82ad-48bf-92b7-cd880ecd947d)
