### ISSUE TITLE
[Feature Request] Monsters only trigger mines when within certain distance of nearest player

### ISSUE THREAD

**Issue by elliott-w** [GoldenKittenPlays/FairAI#2]
It'd be more fun to see the monsters explode in action. E.g. you're running away from a thumper and you lure it into a mine. Otherwise they just explode by themselves from natural wondering and you casually come across a monster corpse - not as fun imo.

**Comment by GoldenKittenPlays** [comment]
I will think on it but I got a lot of other features to work on too. You will see updates anyway so take care I will update here about the request

**Comment by elliott-w** [comment]
@GoldenKittenPlays no demands here, just ideas. Really appreciate all the hard work you've put into your mods <3 I would make my own mods but I have no experience in Unity/game dev. Very daunting to get started :s

**Comment by GoldenKittenPlays** [comment]
> @GoldenKittenPlays no demands here, just ideas. Really appreciate all the hard work you've put into your mods <3 I would make my own mods but I have no experience in Unity/game dev. Very daunting to get started :s

I mean you can always join the Lethal Company modding discord. They are very friendly and seem to like helping devs get started on modding. Thank you for your appreciation

**Comment by GoldenKittenPlays** [comment]
This is now a feature have fun <3
