### ISSUE TITLE
[Feature Request] Turret bullets damage monsters too

### ISSUE THREAD

**Issue by elliott-w** [GoldenKittenPlays/FairAI#3]
You could lure turrets into shooting enemies that are chasing you. Or you could smack the turret (that's near an enemy) with a shovel and run ;D

**Comment by GoldenKittenPlays** [comment]
Already in the works

**Comment by GoldenKittenPlays** [comment]
It is now a feature of Fair AI. Happy playing nya

**Comment by elliott-w** [comment]
@GoldenKittenPlays legend! Could we get a config option to disable turret automatically targeting/shooting at enemies? I just want the bullets to damage them, otherwise I think it's too OP.

**Comment by GoldenKittenPlays** [comment]
> @GoldenKittenPlays legend! Could we get a config option to disable turret automatically targeting/shooting at enemies? I just want the bullets to damage them, otherwise I think it's too OP.

Already in the idea box. I am currently all done for now but I plan to do more on it tomorrow. I plan to make it the same as how my mine works. Either you allow the turret to kill the mob or not. If it is not then it will not target enemies but if it can kill it will target enemies
