### ISSUE TITLE
Turrets turned into semi auto?

### ISSUE THREAD

**Issue by Simpostorr** [GoldenKittenPlays/FairAI#4]
Hi, I have recently noticed that turrets behave differently and now act as one shotdealing ~65 HP damage instead of automatic shooting. Is this made on purpose to be more effective for monsters? Would there be an option in config file in order to tweak the turrets AI to act more like in Vanilla? Was the mod not working properly before adding this feature? I would like to get a feedback of it.

I love the mod itself tho, I just wish I would be able get the turrets to work as before.

**Comment by GoldenKittenPlays** [comment]
This is still in beta so more customizable turret ai to act more like vanilla is still in the works. I am sorry that it acts that way but the turret ai working at all was a huge success for me. ANSWER: Turrets are semi auto when going for players but full auto when going for enemies. Future updates will hopefully make that configurable.

**Comment by Simpostorr** [comment]
Thank you for response, I bet It's challenging to make AI work properly, you don't need to apologize for anything. I love the mod itself and I appreciate your work :D Keep it up, I'm looking up for the new updates!

**Comment by GoldenKittenPlays** [comment]
> Thank you for response, I bet It's challenging to make AI work properly, you don't need to apologize for anything. I love the mod itself and I appreciate your work :D Keep it up, I'm looking up for the new updates!

The turret is now back to normal ai for now but will damage enemies. Meaning it is full auto and will only target the player but it will now do the same damage to enemies in the line of fire. Happy playing
