### ISSUE TITLE
Mod not functional

### ISSUE THREAD

**Issue by Gamersxp6248** [GoldenKittenPlays/FairAI#5]
Mod cannot be used unless whatever the hell a "boomba" is, happens to also be installed. Can the mod default to not affect boombas until either ensuring they exist first or atleast are intentionally enabled in the config? if this option already exists in the config, it defaults to true and the config won't generate because the mod cannot initialized succesfully due to the aforementioned error.

**Comment by GoldenKittenPlays** [comment]
> Mod cannot be used unless whatever the hell a "boomba" is, happens to also be installed. Can the mod default to not affect boombas until either ensuring they exist first or atleast are intentionally enabled in the config? if this option already exists in the config, it defaults to true and the config won't generate because the mod cannot initialized succesfully due to the aforementioned error.

Thank you for telling me this. Strange someone else said they didnt have to have the mod. I will ask around in the discord of the lethal modding community because I am not even depending on that mod as a hard dependency so my mod should load fine. I will get it worked out I am sorry it went that way for you

**Comment by SophisticaSean** [comment]
There is an error without Lethal Things, but otherwise the mod works fine even with this error and just this mod installed for me:

```
[Info   :GoldenKitten.FairAI] Fair AI initiated!
[Error  : Unity Log] TypeLoadException: Could not load type LethalThings.RoombaAI, LethalThings, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
Stack trace:
System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) (at <787acc3c9a4c471ba7d971300105af24>:IL_0013)
System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) (at <787acc3c9a4c471ba7d971300105af24>:IL_0037)
System.RuntimeType.GetCustomAttributes (System.Boolean inherit) (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
HarmonyLib.HarmonyMethodExtensions.GetFromType (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
HarmonyLib.PatchClassProcessor..ctor (HarmonyLib.Harmony instance, System.Type type, System.Boolean allowUnannotatedType) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0030)
HarmonyLib.Harmony.CreateClassProcessor (System.Type type, System.Boolean allowUnannotatedType) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
HarmonyLib.Harmony.PatchAll (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
FairAI.Plugin.Awake () (at <06b083dedfda4faf97f1c623dfb73e13>:IL_00A5)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()
```

**Comment by GoldenKittenPlays** [comment]
> There is an error without Lethal Things, but otherwise the mod works fine even with this error and just this mod installed for me:
> 
> ```
> [Info   :GoldenKitten.FairAI] Fair AI initiated!
> [Error  : Unity Log] TypeLoadException: Could not load type LethalThings.RoombaAI, LethalThings, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
> Stack trace:
> System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) (at <787acc3c9a4c471ba7d971300105af24>:IL_0013)
> System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) (at <787acc3c9a4c471ba7d971300105af24>:IL_0037)
> System.RuntimeType.GetCustomAttributes (System.Boolean inherit) (at <787acc3c9a4c471ba7d971300105af24>:IL_0000)
> HarmonyLib.HarmonyMethodExtensions.GetFromType (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
> HarmonyLib.PatchClassProcessor..ctor (HarmonyLib.Harmony instance, System.Type type, System.Boolean allowUnannotatedType) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0030)
> HarmonyLib.Harmony.CreateClassProcessor (System.Type type, System.Boolean allowUnannotatedType) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
> HarmonyLib.Harmony.PatchAll (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
> FairAI.Plugin.Awake () (at <06b083dedfda4faf97f1c623dfb73e13>:IL_00A5)
> UnityEngine.GameObject:AddComponent(Type)
> BepInEx.Bootstrap.Chainloader:Start()
> UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()
> ```

That is what I heard but I mean I was not fully sure. Thanks for the extra info it always helps getting more feedback

**Comment by Gamersxp6248** [comment]
The error in question stops this mod from correctly initializing for me

**Comment by GoldenKittenPlays** [comment]
> The error in question stops this mod from correctly initializing for me

I will figure it out soon sorry for the issues

**Comment by GoldenKittenPlays** [comment]
> The error in question stops this mod from correctly initializing for me

So this error with the new update should probably be resolved. Come back here and let me know if it is not but I tested it and it seems to show no error at all with or without the other mod installed
