### ISSUE TITLE
Broken turrets

### ISSUE THREAD

**Issue by user7562** [GoldenKittenPlays/FairAI#6]
when turrets lock onto a target, they shoot 1 bullet then pause for a while, after that they try to shoot again but it pauses again. it gets even more buggy when it targets a npc, they shoot for a split seccond then stop and repeat. the rapid fire mode that the turrets have in vanilla is completely gone, fix pls

**Comment by GoldenKittenPlays** [comment]
Are you using the most recent version of the mod. I released it a couple hours ago and it is back to full auto

**Comment by GoldenKittenPlays** [comment]
I have now added a beta release of the turret ai but the turret ai lets you where enemies as hats. Will fix this but otherwise the turret ai itself is fixed lol
