### ISSUE TITLE
Monster Names In Config

### ISSUE THREAD

**Issue by nephatrine** [GoldenKittenPlays/FairAI#7]
It would be nice if the config listed the actual names of the monsters instead of the internal names (i.e. Bracken instead of FlowerMan). I managed to put together what each entry corresponds to except for these: Walker, Maggie, RedPill. Are those mobs from other mods? I've got no idea what those represent.

**Comment by GoldenKittenPlays** [comment]
I do not really know the common names for them so I would have to take my time on that but it is definitely something I will work on thank you so much for the suggestion
