### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by WhisperingR** [GoldenKittenPlays/FairAI#8]
Ayo man, thanks for the mods, they're a mainstay on my modpacks. I noticed on the Thunderstore page + changelogs you've said you lost your job, and could use some donations rn. Question is, do you have anything set up? A Ko-fi or something? I'd be happy to give you a tip! (If you do have a Ko-fi, link it on Thunderstore! I'm sure there's more people that'd be okay with a donation, but aren't willing to go through this effort)

Sorry for making an issue here btw, could not find anywhere else to get in touch with you.

**Comment by GoldenKittenPlays** [comment]
> Ayo man, thanks for the mods, they're a mainstay on my modpacks. I noticed on the Thunderstore page + changelogs you've said you lost your job, and could use some donations rn. Question is, do you have anything set up? A Ko-fi or something? I'd be happy to give you a tip! (If you do have a Ko-fi, link it on Thunderstore! I'm sure there's more people that'd be okay with a donation, but aren't willing to go through this effort)
> 
> Sorry for making an issue here btw, could not find anywhere else to get in touch with you.

Ah the donation link is actually attached to the mod lol. Thank you very much for enjoying my mods it means a lot to me that you even use them. I usually use the one that is attached to all my mods but if you want a ko-fi page I also have one.                     [Here](https://ko-fi.com/goldenkitten)
